#!/bin/bash
# Installs asdf-managed package versions
set -e

if [ "$1" = "--debug" ]; then
  shift
  PRINT_DEBUG="1"
  set -x
fi

warn() { echo "$@" >&2; }
abort() { EXPECTED_EXIT="1"; warn "$@"; exit 1; }

cleanup() {
  set +e
  if [ -n "$EXPECTED_EXIT" ]; then
    return
  fi
  warn "Error: $(basename $0) failed!"
  if [ -z "$PRINT_DEBUG" ]; then
    warn "For debugging output run:"
    warn "  $0 --debug"
  fi
}
trap "cleanup" EXIT

log_step() {
  if [ "x$PRINT_DEBUG" = "x1" ]; then
    echo "==> $1"
  fi
}

log_step "Checking if asdf is installed..."
if ! which asdf &>/dev/null; then
  abort "Error: you need to 'brew install asdf'!"
fi
log_step "Checking for .tool-versions file..."
if [ ! -f .tool-versions ]; then
  abort "Error: you need a '.tool-versions' file to install packages"
fi

log_step "Reading plugins from .tool-versions..."
for plugin in $(cat .tool-versions | awk '{print $1}'); do
  if [ -z $(asdf plugin list | grep $plugin) ]; then
    asdf plugin add $plugin
  fi
done

if [ ! -z "$(grep nodejs .tool-versions)" ]; then
  log_step "Setting up Node.js dependencies..."
  brew bundle --file=- <<EOF
brew "gpg"
EOF

  bash ~/.asdf/plugins/nodejs/bin/import-release-team-keyring
fi
log_step "Installing package versions with asdf..."
(
  for var_override in $( env | grep -E '^ASDF_INSTALL_VAR_[^=]+=' ); do
    var="${var_override#ASDF_INSTALL_VAR_}"
    export "${var}=${!var_override@Q}"
  done
  asdf install
)

if [ ! -z "$(grep ruby .tool-versions)" ]; then
  log_step "Checking Ruby bundler installation..."
  (asdf which bundle &>/dev/null && bundle -v &>/dev/null) || {
    asdf exec ruby -S gem install bundler
  }
fi

EXPECTED_EXIT="1"
exit 0
